#!/usr/bin/env php
<?php

/**
 * Copyright 2017 Rafal Zajac <rzajac@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

use Kicaj\Ttg\Cmd\TtgCmd;
use Symfony\Component\Console\Application;

foreach (
    [
        __DIR__ . '/../../autoload.php',
        __DIR__ . '/../vendor/autoload.php',
        __DIR__ . '/vendor/autoload.php',
    ] as $file) {
    if (file_exists($file)) {
        /** @noinspection PhpIncludeInspection */
        $classLoader = require $file;
        break;
    }
}

$app = new Application('Time table generator.', '1.0.0');

try {
    $app->add(new TtgCmd());
    $app->setDefaultCommand('ttg', true);
    $app->run();
} catch (Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}
